import type { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema20260919000000 implements MigrationInterface {
  name = "InitialSchema20260919000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TYPE user_role AS ENUM ('admin', 'editor');
      CREATE TYPE article_status AS ENUM ('draft', 'published');
      CREATE TYPE video_status AS ENUM ('draft', 'published');
      CREATE TYPE live_status AS ENUM ('live', 'offline');
      CREATE TYPE media_type AS ENUM ('image', 'video');
      CREATE TYPE ad_type AS ENUM ('banner', 'text', 'sponsored');
      CREATE TYPE ad_placement AS ENUM (
        'header', 'below-hero', 'sidebar', 'in-feed', 'in-content', 'popup'
      );
    `);

    await queryRunner.query(`
      CREATE TABLE users (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email         VARCHAR(255) NOT NULL,
        password_hash VARCHAR(255) NOT NULL,
        full_name     VARCHAR(200) NOT NULL,
        role          user_role NOT NULL DEFAULT 'editor',
        created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE UNIQUE INDEX uq_users_email ON users (lower(email));

      CREATE TABLE categories (
        id             SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug           VARCHAR(50) NOT NULL,
        name_bn        VARCHAR(100) NOT NULL,
        name_en        VARCHAR(100) NOT NULL,
        description_bn TEXT,
        description_en TEXT,
        color          VARCHAR(20) NOT NULL DEFAULT '#e2231a',
        parent_id      SMALLINT,
        created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE UNIQUE INDEX uq_categories_slug ON categories (slug);
      ALTER TABLE categories
        ADD CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE SET NULL;

      CREATE TABLE tags (
        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug       VARCHAR(100) NOT NULL,
        name       VARCHAR(100) NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE UNIQUE INDEX uq_tags_slug ON tags (slug);

      CREATE TABLE media (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        filename    VARCHAR(255) NOT NULL,
        url         TEXT NOT NULL,
        storage_key VARCHAR(255),
        type        media_type NOT NULL DEFAULT 'image',
        mime_type   VARCHAR(127),
        size_bytes  BIGINT,
        width       INTEGER,
        height      INTEGER,
        alt         VARCHAR(300),
        uploader_id BIGINT,
        created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE INDEX ix_media_type_created ON media (type, created_at DESC);
      ALTER TABLE media
        ADD CONSTRAINT fk_media_uploader
        FOREIGN KEY (uploader_id) REFERENCES users (id) ON DELETE SET NULL;

      CREATE TABLE articles (
        id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug             VARCHAR(200) NOT NULL,
        category_id      SMALLINT NOT NULL,
        author_id        BIGINT,
        created_by       BIGINT,
        updated_by       BIGINT,
        published_by     BIGINT,
        status           article_status NOT NULL DEFAULT 'draft',
        is_featured      BOOLEAN NOT NULL DEFAULT FALSE,
        is_breaking      BOOLEAN NOT NULL DEFAULT FALSE,
        published_at     TIMESTAMPTZ,
        featured_media_id BIGINT,
        created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
        deleted_at       TIMESTAMPTZ
      );
      CREATE UNIQUE INDEX uq_articles_slug ON articles (slug);
      CREATE INDEX ix_articles_feed ON articles (status, published_at DESC) WHERE deleted_at IS NULL;
      CREATE INDEX ix_articles_feed_featured_partial
        ON articles (status, is_featured, published_at DESC)
        WHERE is_featured = TRUE AND deleted_at IS NULL;
      CREATE INDEX ix_articles_feed_breaking_partial
        ON articles (status, is_breaking, published_at DESC)
        WHERE is_breaking = TRUE AND deleted_at IS NULL;
      CREATE INDEX ix_articles_category_feed
        ON articles (category_id, status, published_at DESC) WHERE deleted_at IS NULL;
      CREATE INDEX ix_articles_author_feed
        ON articles (author_id, published_at DESC) WHERE deleted_at IS NULL;
      ALTER TABLE articles
        ADD CONSTRAINT fk_articles_category
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT;
      ALTER TABLE articles
        ADD CONSTRAINT fk_articles_author
        FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL;
      ALTER TABLE articles
        ADD CONSTRAINT fk_articles_created_by
        FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL;
      ALTER TABLE articles
        ADD CONSTRAINT fk_articles_updated_by
        FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL;
      ALTER TABLE articles
        ADD CONSTRAINT fk_articles_published_by
        FOREIGN KEY (published_by) REFERENCES users (id) ON DELETE SET NULL;
      ALTER TABLE articles
        ADD CONSTRAINT fk_articles_featured_media
        FOREIGN KEY (featured_media_id) REFERENCES media (id) ON DELETE SET NULL;

      CREATE TABLE article_contents (
        article_id        BIGINT NOT NULL,
        locale            CHAR(2) NOT NULL,
        title             VARCHAR(500) NOT NULL,
        summary           TEXT NOT NULL,
        body              TEXT NOT NULL,
        read_time_minutes SMALLINT,
        search_tsv        TSVECTOR GENERATED ALWAYS AS (
                          setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
                          setweight(to_tsvector('simple', coalesce(summary, '')), 'B') ||
                          setweight(to_tsvector('simple', coalesce(body, '')), 'A')
        ) STORED,
        created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (article_id, locale),
        CONSTRAINT ck_article_contents_locale CHECK (locale IN ('bn', 'en'))
      );
      CREATE INDEX ix_article_contents_search_tsv
        ON article_contents USING GIN (search_tsv);
      ALTER TABLE article_contents
        ADD CONSTRAINT fk_article_contents_article
        FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE;

      CREATE TABLE article_tags (
        article_id BIGINT NOT NULL,
        tag_id     BIGINT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (article_id, tag_id)
      );
      CREATE INDEX ix_article_tags_tag ON article_tags (tag_id);
      ALTER TABLE article_tags
        ADD CONSTRAINT fk_article_tags_article
        FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE;
      ALTER TABLE article_tags
        ADD CONSTRAINT fk_article_tags_tag
        FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE;

      CREATE TABLE videos (
        id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug             VARCHAR(200) NOT NULL,
        category_id      SMALLINT NOT NULL,
        author_id        BIGINT,
        poster_media_id  BIGINT,
        title_bn         VARCHAR(300) NOT NULL,
        title_en         VARCHAR(300) NOT NULL,
        summary_bn       TEXT NOT NULL,
        summary_en       TEXT NOT NULL,
        video_url        TEXT NOT NULL,
        duration_seconds INTEGER NOT NULL DEFAULT 0,
        views_count      INTEGER NOT NULL DEFAULT 0,
        featured         BOOLEAN NOT NULL DEFAULT FALSE,
        status           video_status NOT NULL DEFAULT 'draft',
        published_at     TIMESTAMPTZ,
        created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
        deleted_at       TIMESTAMPTZ
      );
      CREATE UNIQUE INDEX uq_videos_slug ON videos (slug);
      CREATE INDEX ix_videos_feed ON videos (status, published_at DESC) WHERE deleted_at IS NULL;
      CREATE INDEX ix_videos_category_feed
        ON videos (category_id, status, published_at DESC) WHERE deleted_at IS NULL;
      ALTER TABLE videos
        ADD CONSTRAINT fk_videos_category
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT;
      ALTER TABLE videos
        ADD CONSTRAINT fk_videos_author
        FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL;
      ALTER TABLE videos
        ADD CONSTRAINT fk_videos_poster_media
        FOREIGN KEY (poster_media_id) REFERENCES media (id) ON DELETE SET NULL;

      CREATE TABLE live_streams (
        id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug             VARCHAR(200) NOT NULL,
        category_id      SMALLINT NOT NULL,
        poster_media_id  BIGINT,
        title_bn         VARCHAR(300) NOT NULL,
        title_en         VARCHAR(300) NOT NULL,
        description_bn   TEXT NOT NULL,
        description_en   TEXT NOT NULL,
        stream_url       TEXT,
        is_active        BOOLEAN NOT NULL DEFAULT FALSE,
        status           live_status NOT NULL DEFAULT 'offline',
        started_at       TIMESTAMPTZ,
        viewer_count     INTEGER NOT NULL DEFAULT 0,
        created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE UNIQUE INDEX uq_live_streams_slug ON live_streams (slug);
      -- At most one active live stream.
      CREATE UNIQUE INDEX uq_live_streams_single_active ON live_streams ((TRUE)) WHERE is_active = TRUE;
      ALTER TABLE live_streams
        ADD CONSTRAINT fk_live_streams_category
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT;
      ALTER TABLE live_streams
        ADD CONSTRAINT fk_live_streams_poster_media
        FOREIGN KEY (poster_media_id) REFERENCES media (id) ON DELETE SET NULL;

      CREATE TABLE advertisements (
        id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug             VARCHAR(200) NOT NULL,
        type             ad_type NOT NULL DEFAULT 'banner',
        title_bn         VARCHAR(300) NOT NULL,
        title_en         VARCHAR(300) NOT NULL,
        description_bn   TEXT,
        description_en   TEXT,
        image_media_id   BIGINT,
        target_url       TEXT NOT NULL,
        alt              VARCHAR(300),
        is_active        BOOLEAN NOT NULL DEFAULT TRUE,
        start_date       DATE,
        end_date         DATE,
        created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
      );
      CREATE UNIQUE INDEX uq_advertisements_slug ON advertisements (slug);
      CREATE INDEX ix_advertisements_active_dates ON advertisements (is_active, start_date, end_date);
      ALTER TABLE advertisements
        ADD CONSTRAINT fk_advertisements_image
        FOREIGN KEY (image_media_id) REFERENCES media (id) ON DELETE SET NULL;

      CREATE TABLE advertisement_placements (
        advertisement_id BIGINT NOT NULL,
        placement        ad_placement NOT NULL,
        created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
        PRIMARY KEY (advertisement_id, placement)
      );
      CREATE INDEX ix_advertisement_placements_placement
        ON advertisement_placements (placement);
      ALTER TABLE advertisement_placements
        ADD CONSTRAINT fk_ad_placements_advertisement
        FOREIGN KEY (advertisement_id) REFERENCES advertisements (id) ON DELETE CASCADE;

      CREATE TABLE site_settings (
        id                    SMALLINT PRIMARY KEY,
        site_name_bn          VARCHAR(200) NOT NULL,
        site_name_en          VARCHAR(200) NOT NULL,
        tagline_bn            VARCHAR(300) NOT NULL,
        tagline_en            VARCHAR(300) NOT NULL,
        logo_url              TEXT NOT NULL,
        favicon_url           TEXT NOT NULL,
        newsletter_email      VARCHAR(255),
        editor_name_bn        VARCHAR(200) NOT NULL,
        editor_name_en        VARCHAR(200) NOT NULL,
        facebook_url          TEXT,
        twitter_url           TEXT,
        instagram_url         TEXT,
        youtube_url           TEXT,
        latest_articles_count INTEGER NOT NULL DEFAULT 8,
        most_read_count       INTEGER NOT NULL DEFAULT 5,
        breaking_max_items    INTEGER NOT NULL DEFAULT 10,
        default_live_slug     VARCHAR(200),
        meta_title_bn         VARCHAR(300) NOT NULL,
        meta_title_en         VARCHAR(300) NOT NULL,
        meta_description_bn   TEXT NOT NULL,
        meta_description_en   TEXT NOT NULL,
        og_image_url          TEXT,
        metadata_base_url     TEXT,
        updated_by            BIGINT,
        created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT ck_site_settings_single_row CHECK (id = 1)
      );
      ALTER TABLE site_settings
        ADD CONSTRAINT fk_site_settings_updated_by
        FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE IF EXISTS site_settings;
      DROP TABLE IF EXISTS advertisement_placements;
      DROP TABLE IF EXISTS advertisements;
      DROP TABLE IF EXISTS live_streams;
      DROP TABLE IF EXISTS videos;
      DROP TABLE IF EXISTS article_tags;
      DROP TABLE IF EXISTS article_contents;
      DROP TABLE IF EXISTS articles;
      DROP TABLE IF EXISTS media;
      DROP TABLE IF EXISTS tags;
      DROP TABLE IF EXISTS categories;
      DROP TABLE IF EXISTS users;
      DROP TYPE IF EXISTS ad_placement;
      DROP TYPE IF EXISTS ad_type;
      DROP TYPE IF EXISTS media_type;
      DROP TYPE IF EXISTS live_status;
      DROP TYPE IF EXISTS video_status;
      DROP TYPE IF EXISTS article_status;
      DROP TYPE IF EXISTS user_role;
    `);
  }
}