import type { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Adds the server-side session store used by the admin authentication layer.
 *
 * Sessions hold only a SHA-256 hash of the session identifier; the raw
 * identifier lives exclusively in the HttpOnly authentication cookie. The
 * user FK is ON DELETE CASCADE so deleting a user revokes their sessions.
 *
 * Indexes:
 *   - token_hash unique index  -> O(1) session lookup on every request
 *   - user_id                  -> "sessions per user" listing / cleanup
 *   - expires_at               -> periodic cleanup of expired sessions
 */
export class AddAuthSessions20260921000000 implements MigrationInterface {
  name = "AddAuthSessions20260921000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE sessions (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id      BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
        token_hash   CHAR(64) NOT NULL,
        expires_at   TIMESTAMPTZ NOT NULL,
        created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
        last_used_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        revoked_at   TIMESTAMPTZ
      );
      CREATE UNIQUE INDEX uq_sessions_token_hash ON sessions (token_hash);
      CREATE INDEX idx_sessions_user_id ON sessions (user_id);
      CREATE INDEX idx_sessions_expires_at ON sessions (expires_at);
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS sessions;`);
  }
}